version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./TelegramBot:/app/TelegramBot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      CHAT_ID: ${CHAT_ID}
